import os
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
PROJECT_CACHE = PROJECT_ROOT / ".cache"
PROJECT_CACHE.mkdir(parents=True, exist_ok=True)

# Menus de sortie centralisés. Les numéros gardent un ordre stable dans Finder
# et évitent que chaque script invente son propre dossier à la racine.
SORTIES_ROOT = PROJECT_ROOT / "sorties"
SORTIES_RECHERCHE_MODELE = SORTIES_ROOT / "01_RECHERCHE_MODELE"
SORTIES_HYPERPARAMETRES = SORTIES_RECHERCHE_MODELE / "01_HYPERPARAMETRES"
SORTIES_STABILITE = SORTIES_RECHERCHE_MODELE / "02_STABILITE"
SORTIES_RECHERCHE_ARCHITECTURES = (
    SORTIES_RECHERCHE_MODELE / "03_RECHERCHE_ARCHITECTURES"
)
SORTIES_ENTRAINEMENTS_MANUELS = (
    SORTIES_RECHERCHE_MODELE / "04_ENTRAINEMENTS_MANUELS"
)

SORTIES_EVALUATION_MODELE = SORTIES_ROOT / "02_EVALUATION_MODELE"
SORTIES_PERFORMANCES_PAR_CHIFFRE = (
    SORTIES_EVALUATION_MODELE / "01_PERFORMANCES_PAR_CHIFFRE"
)
SORTIES_CHIFFRES_MOYENS = (
    SORTIES_EVALUATION_MODELE / "02_CHIFFRES_MOYENS"
)

SORTIES_TESTS_PHOTOS = SORTIES_ROOT / "03_TESTS_PHOTOS"
SORTIES_TESTS_TERRAIN = SORTIES_TESTS_PHOTOS / "01_TESTS_TERRAIN"
SORTIES_CASCADE_TOP_N = SORTIES_TESTS_PHOTOS / "02_CASCADE_TOP_N"

DONNEES_TESTS_TERRAIN = PROJECT_ROOT / "donnees" / "tests_terrain_a_analyser"
DONNEES_CASCADE_TOP_N = PROJECT_ROOT / "donnees" / "tests_cascade_top_n"

MODELES_VALIDES = PROJECT_ROOT / "modeles" / "modeles_valides"
MODELES_EN_COURS = PROJECT_ROOT / "modeles" / "modeles_en_cours"
MODELES_RECHERCHE_ARCHITECTURES = (
    PROJECT_ROOT / "modeles" / "recherche_architectures"
)

os.environ.setdefault("KERAS_BACKEND", "tensorflow")
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
os.environ.setdefault("XDG_CACHE_HOME", str(PROJECT_CACHE))
os.environ.setdefault("MPLCONFIGDIR", str(PROJECT_CACHE / "matplotlib"))
